### ISSUE TITLE
Error when all: true in defaults

### ISSUE THREAD

**Issue by tofumarinado** [lts-beratung/capitana#10]
```
❯ capitana --config runtime.capitanarc
Error: Stage "undefined" not included in the ones specified in the config file:
  "build,push".
    at assertStageIsValid (/Users/vike/.nvm/versions/node/v10.15.3/lib/node_modules/capitana/src/index.js:141:9)
    at module.exports (/Users/vike/.nvm/versions/node/v10.15.3/lib/node_modules/capitana/src/index.js:25:2)
    at /Users/vike/.nvm/versions/node/v10.15.3/lib/node_modules/capitana/src/cli.js:134:10
    at Object.<anonymous> (/Users/vike/.nvm/versions/node/v10.15.3/lib/node_modules/capitana/src/cli.js:142:3)
    at Module._compile (internal/modules/cjs/loader.js:701:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:712:10)
    at Module.load (internal/modules/cjs/loader.js:600:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:539:12)
    at Function.Module._load (internal/modules/cjs/loader.js:531:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:754:12)
```

```
runtime.capitanarc
variables:
  defaults:
    verbose: true
    break: true
    all: true
    full: true
microservices:
  runtime: ~
stages:
  build:
    ...
  push:
    ...
```

Maybe checking for default variables earlier could help solve this issue.
